version: "3.9"

services:
  meeting-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microsoft
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OBS_HOST=${OBS_HOST}
      - OBS_PORT=${OBS_PORT}
      - OBS_PASSWORD=${OBS_PASSWORD}
    volumes:
      - ./recordings:/app/recordings
      - ./transcripts:/app/transcripts
      - ./summaries:/app/summaries
    restart: "no"
